In [44]:
import numpy as np
an_array=np.array([3,33,333])  #create a rank 1 array
print(type(an_array))          #the type of an ndarray is :''<class''numpy.

<class 'numpy.ndarray'>


In [45]:
print(an_array.shape)  #its has only one dimention

(3,)


In [46]:
print(an_array[0],an_array[1],an_array[2])#bcoz this is 1-rank,we need only one index to access each element

3 33 333


In [47]:
an_array[0]=888    #ndarray is mutable,0th position value is changed here
print(an_array)

[888  33 333]


In [48]:
an_array2=np.array([[3,33,333]]) # matrix
an_array2.shape

(1, 3)

In [49]:
another=np.array([[11,12,13],[21,22,23]]) #create a rank 2
print(another)
print("the shape is 2 rows,3 columns:",another.shape)
print("accessing elements[0,0],[0,1],and [1,0] of the ndarray:",another[0,0],",",another[0,1],",",another[1,0])

#variable will always be out of inverted commas in print statement because they are going to change
#values which are specific/static will always be in inverted commas
#as in print statements


[[11 12 13]
 [21 22 23]]
the shape is 2 rows,3 columns: (2, 3)
accessing elements[0,0],[0,1],and [1,0] of the ndarray: 11 , 12 , 21


In [88]:
#create a 2*2 array filled with 9.0
ex2=np.full((3,4),9.0) #inbuild func
print(ex2)

[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [51]:
#create a 2*2 array of zeros
ex1=np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [52]:
#create a 2*2 matrix with diagonal 1s and the others 0
ex3=np.eye(4,4)
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
#create an array of ones
ex4=np.ones((2,3))
print(ex4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [54]:
#notice that the above ndarray (ex4)is actually rank 2,it is a 2x1 array
print(ex4.shape)
#which means we need to use two indexes to access an element
print()
print(ex4[0,0])

(2, 3)

1.0


In [55]:
#create an array of random floats between 0 and 1
ex5=np.random.random((3,4))
print(ex5)

[[0.06829891 0.58495112 0.15446467 0.81114818]
 [0.26450995 0.21828359 0.56090975 0.77667322]
 [0.02545859 0.51005369 0.07667489 0.36924329]]


In [56]:
import numpy as np
#rank 2 array of shape (3,4)
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [57]:
a_slice=an_array[0:2,1:3]
#select zero and one rows, 1 nad 2 column
print(an_array[0:3,1:2])   #[rows range - select 0,1,2 values , columns range - select 1 value only]
print(a_slice)

[[12]
 [22]
 [32]]
[[12 13]
 [22 23]]


In [58]:
print("Before:" ,an_array[0,1])#inspect the element at 0,1
a_slice[0,0]=1000 #a_slice[0,0] is the samepiece of data as an_array[0,1]
print("After:" ,an_array[0,1])

Before: 12
After: 1000


In [59]:
an_array

array([[  11, 1000,   13,   14],
       [  21,   22,   23,   24],
       [  31,   32,   33,   34]])

In [60]:
a_slice

array([[1000,   13],
       [  22,   23]])

In [61]:
an_array

array([[  11, 1000,   13,   14],
       [  21,   22,   23,   24],
       [  31,   32,   33,   34]])

In [62]:
import numpy as np
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]]) #array shape (3,4)
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [63]:
#using both integerindexing and slicing generates an array of lower rank
row_rank1=an_array[1,:]#rank1 view
print(row_rank1,row_rank1.shape) #ntice only a single[]

[21 22 23 24] (4,)


In [64]:
#slicing alone:generates an array of the same rank as the an_array
row_rank2=an_array[1:2, :]#rank2 view
print(row_rank2,row_rank2.shape) #ntice only a single[]

[[21 22 23 24]] (1, 4)


In [65]:
column_rank1=an_array[:,1]
print(column_rank1,column_rank1.shape)

[12 22 32] (3,)


In [66]:
col_rank1=an_array[:,1]
col_rank2=an_array[:,1:2]
print(col_rank1,col_rank1.shape)
print()
print(col_rank2,col_rank2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [67]:
an_array=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print('Original Array')
print(an_array)

Original Array
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [68]:
col_indices=np.array([0,1,2,0])
print('\nCol indices picked:',col_indices)

row_indices=np.arange(4)
print('\nRows indices picked:',row_indices)


Col indices picked: [0 1 2 0]

Rows indices picked: [0 1 2 3]


In [69]:
for i,j in zip (row_indices,col_indices): #examine the pairing of roe_indices n col_indices.
    print(i,",",j)
    
    '''for i in row_indices
    for j incol_indices'''

0 , 0
1 , 1
2 , 2
3 , 0


In [70]:
#select one element from each row
print ('values in the array at those indices:',an_array[row_indices,col_indices])
#an_array[0, 0], an_array[1,1],an_array[2, 2], an_array[3,0] = an_array[row_indices, col_indices]

values in the array at those indices: [11 22 33 41]


In [71]:
#change one element from each row using the indices selected
an_array[row_indices,col_indices] +=1000  #a=a+10 is sam as a+=10
print('\nchanged Array:')
an_array


changed Array:


array([[1011,   12,   13],
       [  21, 1022,   23],
       [  31,   32, 1033],
       [1041,   42,   43]])

In [72]:
#create a3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [73]:
#create a filter which will be boolean values 
filter=(an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [74]:
#we can now select just those elements whivh meet that creteria

print(an_array[filter]) #values that r greater than 5


[21 22 31 32]


In [75]:
an_array[an_array>15]  #for short we could hv just used this approach without declaring filter

array([21, 22, 31, 32])

In [76]:
an_array[an_array%2==0]+=100  #adding 100 to even values
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [77]:
an_array=np.array([2,3,6,7,8,9])
print(an_array)


[2 3 6 7 8 9]


In [78]:
slice1=an_array[2:4]
print(slice1)

[6 7]


In [79]:
slice2=an_array[4]
print(slice2)

8


In [80]:
a=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [84]:
slice=a[0:2,1:3]  # 0th row & 1st row,1st column & 2rd column
print(slice)

[[12 13]
 [22 23]]


In [85]:
slice2=a[0:2,2:4]  #0th row n 1st row,2nd column n 3rd column
print(slice2)

[[13 14]
 [23 24]]


In [86]:
slice3=a[1:3,2:4]  #1st row n 2nd row ,2nd column n 3rd column
print(slice3)

[[23 24]
 [33 34]]


In [87]:
column1=a[:,2:4]
print(column1)

[[13 14]
 [23 24]
 [33 34]]


In [89]:
ex1=np.array([11,12]) #pythn assign the datatype
print(ex1.dtype)

int32


In [90]:
ex2=np.array([11.0,12.0]) #pythn assign the datatype
print(ex2.dtype)

float64


In [127]:
ex3=np.array([11,12],dtype=np.int64) #you cam also tell pythn to assign the datatype
print(ex3.dtype)
ex3

int64


array([11, 12], dtype=int64)

In [96]:
ex4=np.array([11.1,12.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [97]:
ex5=np.array([11,12],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 12.]


# Arithmetic operations

In [1]:
import numpy as np
x= np.array([[111,112],[121,122]],dtype=np.int)
y= np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


<ipython-input-1-4bd6ca778f4d>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x= np.array([[111,112],[121,122]],dtype=np.int)


In [2]:
#add
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [3]:
#multipy
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [4]:
print(x-y) #substraction

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [5]:
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [6]:
#divide

print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [7]:
#square root
print(np.sqrt(x))


[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [8]:
#exponent(e**x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [9]:
#setup a random 2*5 matrix
arr=10 * np.random.randn(2,5)  #dtype-float 
print(arr)

[[  6.44051497   6.72951466  -6.50520096   5.07273587  -5.98516151]
 [ -4.84405148   1.07337794 -18.15622893  11.40943349  14.59386008]]


In [10]:
#compute the mean for all elemnts
print(arr.mean())

0.9828794126241714


In [11]:
#compute mean by row
print(arr.mean(axis=1))

[1.15048061 0.81527822]


In [12]:
#compute mean by column
print(arr.mean(axis=0))

[  0.79823175   3.9014463  -12.33071495   8.24108468   4.30434928]


In [13]:
#summ all the eemnts
print(arr.sum())

9.828794126241714


In [14]:
#compute the median by rw
print(np.median(arr,axis=1))

[5.07273587 1.07337794]


In [15]:
#compute the median by column
print(np.median(arr,axis=0))

[  0.79823175   3.9014463  -12.33071495   8.24108468   4.30434928]


In [16]:
#create a 10 element array of randoms
unsorted=np.random.randn(10)
print(unsorted)

[-1.08730556 -1.26075637  0.07603809  0.05974765  0.37884166  0.75912952
 -0.21759982  1.20314585 -0.1292695   1.35338811]


In [29]:
sorted=np.array(unsorted)
sorted.sort()  #it will arrange values in ascending order

print("unsorted elments:", unsorted)
print()
print("sorted elements:", sorted)

unsorted elments: [-1.26075637 -1.08730556 -0.21759982 -0.1292695   0.05974765  0.07603809
  0.37884166  0.75912952  1.20314585  1.35338811]

sorted elements: [-1.26075637 -1.08730556 -0.21759982 -0.1292695   0.05974765  0.07603809
  0.37884166  0.75912952  1.20314585  1.35338811]


In [18]:
unsorted.sort()  
print(unsorted)

[-1.26075637 -1.08730556 -0.21759982 -0.1292695   0.05974765  0.07603809
  0.37884166  0.75912952  1.20314585  1.35338811]


In [19]:
#to return unique values
array=np.array([1,2,1,4,2,1,4,2,55])
np.unique(array) 

array([ 1,  2,  4, 55])

In [20]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)


['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [21]:
print(np.intersect1d(s1,s2))  #commom values bwtween s1 n s2


['bulb' 'chair']


In [22]:
print(np.union1d(s1,s2))  #common n uncommon values btw s1 n s2

['bulb' 'chair' 'desk' 'lamp']


In [23]:
print(np.setdiff1d(s1,s2)) #elements in s1 that are not in s2

['desk']


In [24]:
print(np.setdiff1d(s2,s1)) #elements in s2 that are not in s1

['lamp']


In [25]:
print(np.in1d(s1,s2)) #which elements of s1 is also in s2

[False  True  True]


In [32]:
print(np.in1d(s2,s1)) #which elements of s2 is also in s1

[False  True  True]


In [19]:
import numpy as np

start=np.zeros((4,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#create a rank 1 ndarray wth 3 values

add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [21]:
y=start+add_rows  #add to each row of start using broadcasting
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [22]:
add_cols=np.array([[0,1,2,3]])  #4x1 ndarray
add_cols=add_cols.T  # transpose:- converts rows into column n vice versa

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [23]:
y=start+add_cols  #add toeach column of start using broadcasting
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [24]:
#this will just broadcast in both dimensions

add_scalar=np.array([2])
print(start+add_scalar)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [53]:
array1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])   #3x4
array2=np.array([[10,20,30,40]]) #1x4
print(array1)
print()
print (array2)
print()
print(array1+array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[10 20 30 40]]

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [26]:
from numpy import arange
from timeit import Timer  #n

size = 1000000
timeits = 1000

In [27]:
#create thendarray with values 0,1,2,....,size-1
nd_array=arange(size) #arange (4), arange(1000000)
print(type(nd_array))

<class 'numpy.ndarray'>


In [28]:
timer_numpy=Timer("nd_array.sum()" , "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" %
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000815 seconds


In [29]:
#create list with values 0,1,2,...size-1
a_list=list(range(size)) #range(end) 1000000
print(type(a_list))

<class 'list'>


In [30]:
# timer expects the operation as parameter ,here we passsum(a_list)

timer_list=Timer("sum(a_list)" , "from __main__ import a_list")

print("Time taken by list: %f seconds" %
      (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.049878 seconds


# binary format

In [31]:
import numpy as np
x=np.array ([23.23,24.24])

In [32]:
np.save('an_array',x)  #saves value in x to an_array
np.load('an_array.npy')

array([23.23, 24.24])

# Dot product on matrices n inner product on vectors

In [33]:
x2d=np.array([[1,1],[1,1]])  #dot products of 2 matrix
y2d=np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [34]:
a1d=np.array([9,9])  #inner product of 2 vectors
b1d=np.array([10,10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [35]:
#Dot product of arrayn vector

print(x2d.dot(a1d)) # ([9,9]),([[1,1],[1,1]])  [1*9+1*9, 1*9+1*9]= [18,18] 
                                                                #  [18,18]
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


# Sum

In [61]:
#sum elements in the array

ex1=np.array([[11,12],[21,22]])
print(ex1)
print(np.sum(ex1))   #add all members

[[11 12]
 [21 22]]
66


In [37]:
print(np.sum(ex1,axis=0))  #columnwise sum


[32 34]


In [38]:
print(np.sum(ex1,axis=1))  #rowwise sum

[23 43]


In [39]:
x=np.random.randn(8)  #random array
x

array([-0.5325242 , -0.79536885, -0.75763519, -1.44563814, -0.61690522,
        0.48137262,  0.32962343,  0.79230138])

In [40]:
y=np.random.randn(8)  #another random array
y

array([ 0.68504864, -0.88653842,  0.20440641,  1.08035201,  0.20182094,
        0.68682559, -0.31154917,  0.41772444])

In [41]:
np.maximum(x,y)

array([ 0.68504864, -0.79536885,  0.20440641,  1.08035201,  0.20182094,
        0.68682559,  0.32962343,  0.79230138])

In [42]:
# returns elements wise maximum between two arrays
import numpy as np
x=np.random.randn(8)
y=np.random.randn(8)
np.maximum(x,y)


array([1.45794213, 0.11870784, 0.45871359, 0.98294406, 0.99439661,
       1.44571595, 0.54096377, 0.72977702])

In [43]:
#grab values from 0 through 19 in an aray
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
#reshape to be a 4x5 matrix

arr.reshape(4,5)  #5x4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
print(arr.reshape(4,5).T)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [71]:
a=np.array([[1,1,1],[2,2,2],[3,3,3]])
b=np.array([[2,2,3],[2,2,3],[2,2,3]])
print(a)
print()
print(b)
print()
print(np.dot(a,b))
print()
x=np.dot(a,b)
print(x.T)
print()
print(np.add(a,b))

[[1 1 1]
 [2 2 2]
 [3 3 3]]

[[2 2 3]
 [2 2 3]
 [2 2 3]]

[[ 6  6  9]
 [12 12 18]
 [18 18 27]]

[[ 6 12 18]
 [ 6 12 18]
 [ 9 18 27]]

[[3 3 4]
 [4 4 5]
 [5 5 6]]


In [73]:
x1=np.array([1,2,3,4,5])
y1=np.array([11,22,33,44,55])

#where we hv true in filter it will print x1 value n for false y1 value
#this is the wrking of "where" function 

filter=np.array([ True, False,True,False,True])

out=np.where(filter,x1,y1)
print(out)

[ 1 22  3 44  5]


In [82]:
mat=np.random.randn(5,5)
mat
np.where(mat>0.5,1000,-1)

array([[  -1, 1000,   -1,   -1,   -1],
       [  -1,   -1,   -1, 1000,   -1],
       [1000,   -1, 1000,   -1,   -1],
       [  -1, 1000, 1000, 1000,   -1],
       [  -1,   -1,   -1,   -1, 1000]])

In [ ]:
'''
if mat>0.5:
    replace(1000)
else:
    replace(-1)

In [77]:
arr_bools=np.array([True,False,True,False])
arr_bools.any() #is any value true

True

In [78]:
arr_bools.all() #all values true

False

In [79]:
import numpy as np
y=np.random.normal(size=(1,5))
print(y)

[[ 0.33891267 -0.05433426 -0.83300945 -2.42321684  0.56968393]]


In [80]:
z=np.random.randint(low=2,high=50,size=4)
print(z)

[24 30 20 31]


In [81]:
np.random.permutation(z)  #returns a new ordering of elements in z

array([31, 30, 20, 24])

# Normal n uniform distribution

In [83]:
np.random.uniform(size=4)  #uniform distribution

array([0.82200174, 0.89203825, 0.23471517, 0.95444998])

In [84]:
np.random.normal(size=4)  #normal distribution

array([-0.68631334,  0.16786158,  0.67415046, -0.25033824])

# Merging Data sets

In [89]:
K=np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M=np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[30 11]
 [40  9]]

[[29 37]
 [ 3 10]]


In [90]:
np.vstack((K,M))  # join vertically

array([[30, 11],
       [40,  9],
       [29, 37],
       [ 3, 10]])

In [91]:
np.hstack((K,M)) #join horizontally

array([[30, 11, 29, 37],
       [40,  9,  3, 10]])

In [92]:
np.concatenate([K,M],axis=0)

array([[30, 11],
       [40,  9],
       [29, 37],
       [ 3, 10]])

In [93]:
np.concatenate([K,M.T],axis=1)

array([[30, 11, 29,  3],
       [40,  9, 37, 10]])